name: Deploy-application-to-Render

on:
  workflow_run:
    workflows: [Run-unit-tests-using-Pytest]
    types: [completed]

env:
  RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'schedule' &&  github.event.workflow_run.event != 'pull_request'}}
    steps:
      - name: Deploy application to Render
        run: curl "$RENDER_DEPLOY_HOOK"